use std::{
    fs::{self, File},
    io::{self, Write},
    path::{Path, PathBuf},
};

/// Scan the configured sandbox recursively and write a deterministic manifest
/// containing one relative file path per line. The manifest itself is excluded
/// so running the command repeatedly does not change the result.
pub fn create_file_manifest(sandbox_dir: &Path) -> io::Result<PathBuf> {
    fs::create_dir_all(sandbox_dir)?;

    let manifest_path = sandbox_dir.join("sandbox_file_names.txt");
    let mut files = Vec::new();

    collect_files(sandbox_dir, sandbox_dir, &manifest_path, &mut files)?;
    files.sort_by(|a, b| a.to_string_lossy().cmp(&b.to_string_lossy()));

    let mut out = File::create(&manifest_path)?;
    writeln!(out, "# Files in sandbox")?;
    writeln!(out, "# Root: {}", sandbox_dir.display())?;
    writeln!(out, "# Generated by Claude Terminal Bridge")?;
    writeln!(out)?;

    for path in &files {
        writeln!(out, "{}", path.to_string_lossy())?;
    }

    Ok(manifest_path)
}

fn collect_files(
    root: &Path,
    dir: &Path,
    manifest_path: &Path,
    files: &mut Vec<PathBuf>,
) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;

        if file_type.is_symlink() {
            // Avoid following links outside the sandbox.
            continue;
        }

        if file_type.is_dir() {
            collect_files(root, &path, manifest_path, files)?;
        } else if file_type.is_file() && path != manifest_path {
            if let Ok(relative) = path.strip_prefix(root) {
                files.push(relative.to_path_buf());
            }
        }
    }

    Ok(())
}
